### ISSUE TITLE
`b` is a forbidden name in for loops

### ISSUE THREAD

**Issue by lvignoli** [adhocteam/pushup#88]
In a fresh project from `pushup new` (on commit `dc4b44b`), the following `index.up` cannot be built:

```
^for b:=0; b<10; b++ {
    <p>^b</p>
}
```

Output error:

```text
# example/myproject/build
index.up:2: cannot use b (variable of type int) as type io.Writer in argument to io.WriteString:
	int does not implement io.Writer (missing Write method)
index.up:2: cannot use b (variable of type int) as type io.Writer in argument to printEscaped:
	int does not implement io.Writer (missing Write method)
index.up:3: cannot use b (variable of type int) as type io.Writer in argument to io.WriteString:
	int does not implement io.Writer (missing Write method)
build command: building project: building project main executable: exit status 2
```

Changing the variable name to `a` or `i` builds fine.

Observed on a MacBook Pro 2021 (M1 Pro) with macOS 13.1.

**Comment by paulsmith** [comment]
Ouch! I knew someone would stumble on this eventually, apologies. This is due to the code generator not being hygienic, so the code you write in a Pushup page can clash with runtime code needed by Pushup itself. In this case there is literally a [variable named "b"](https://github.com/adhocteam/pushup/blob/main/main.go#L1669) that Pushup uses for outputting the results of expressions.

**Comment by lvignoli** [comment]
Thanks for the very quick fix!

Are there many problematic names? Mangling all of the runtime seems unreasonable, but a larger fix seems necessary.
